### ISSUE TITLE
want a configurable thumb.style["max-width"]

### ISSUE THREAD

**Issue by divinity76** [rejetto/thumbnails#3]
I wish thumb.style["max-width"] was a configurable option.

**Comment by rejetto** [comment]
hey, i guess we don't need an option for that, as you can add any style you want already:
admin panel > custom html > style
```css
img.thumbnail { max-width: 30px }
```

is this ok?
